<?xml version="1.0" encoding="utf-8"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:dlna="urn:schemas-dlna-org:device-1-0">
  	<specVersion>
	    <major>1</major>
	    <minor>0</minor>
  	</specVersion>
  	<URLBase>http://192.168.49.1:38400</URLBase>
  	<device>
		<dlna:X_DLNADOC>DMR-1.50</dlna:X_DLNADOC>
		<UDN></UDN>
		<friendlyName>eHomeMediaCenter</friendlyName>
	    <deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
	    <deviceURL>/deviceDescription/MediaRenderer</deviceURL>
	    <manufacturer>QW</manufacturer>
        <manufacturerURL>http://www.cybergarage.org/</manufacturerURL>
		<modelName>QW Media Renderer</modelName>
	    <modelDescription>QW Media Renderer, DLNA(DMR)</modelDescription>
	    <modelNumber>1.0</modelNumber>
        <modelURL>http://www.cybergarage.org/</modelURL>
		<serialNumber></serialNumber>
	    <iconList>
		 <icon>
            <mimetype>image/png</mimetype>
            <width>120</width>
            <height>120</height>
            <depth>24</depth>
            <url>/icon/0</url>
         </icon>
         <icon>
            <mimetype>image/png</mimetype>
            <width>48</width>
            <height>48</height>
            <depth>24</depth>
            <url>/icon/1</url>
         </icon>
         <icon>
            <mimetype>image/jpeg</mimetype>
            <width>120</width>
            <height>120</height>
            <depth>24</depth>
            <url>/icon/2</url>
         </icon>
         <icon>
            <mimetype>image/jpeg</mimetype>
            <width>48</width>
            <height>48</height>
            <depth>24</depth>
            <url>/icon/3</url>
         </icon>
		</iconList>
	    <serviceList>
	    	<service>
				<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
				<serviceName>ConnectionManager</serviceName>
				<SCPDURL>/serviceDescription/ConnectionManager</SCPDURL>
				<controlURL>/serviceControl/ConnectionManager</controlURL>
				<eventSubURL>/serviceEventing/ConnectionManager</eventSubURL>
			</service>
		  	<service>
			    <serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
			    <serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
			    <serviceName>RenderingControl</serviceName>
			    <SCPDURL>/serviceDescription/RenderingControl</SCPDURL>
			    <controlURL>/serviceControl/RenderingControl</controlURL>
			    <eventSubURL>/serviceEventing/RenderingControl</eventSubURL>
		  	</service>
		  	<service>
			    <serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
			    <serviceName>AVTransport</serviceName>
			    <SCPDURL>/serviceDescription/AVTransport</SCPDURL>
			    <controlURL>/serviceControl/AVTransport</controlURL>
			    <eventSubURL>/serviceEventing/AVTransport</eventSubURL>
		  	</service>
		</serviceList>
	    <presentationURL>/presentation</presentationURL>
  	</device>
</root>
