/*
 * lv_pro_connect_wifi_activity.h
 *
 *  Created on: 2024/09/20
 *      Author: JASON
 */

#ifndef LV_PRO_CONNECT_WIFI_ACTIVITY_H
#define LV_PRO_CONNECT_WIFI_ACTIVITY_H

#include "lv_pro_wifi_common.h"

#if ENABLE_WIFI

#if defined(LV_USE_RESOLUTION_1080P)
#define WIFI_CONNE_WIDGET_HEIGHT_PCT 55
#define WIFI_CONNE_WIDGET_WIDTH_PCT 30

#define WIFI_CONNE_WIDGET_ALIGN_TOP 5
#define WIFI_CONNE_WIDGET_ALIGN_TOP0 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP1 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP2 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP3 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP4 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP5 10
#define WIFI_CONNE_WIDGET_ALIGN_TOP6 5
#define WIFI_CONNE_WIDGET_ALIGN_TOP7 0

#define WIFI_CONN_WIDGET_SET_H 1
#define WIFI_MAX_PWD_LEN 64
#else
#define WIFI_CONNE_WIDGET_HEIGHT_PCT 55
#define WIFI_CONNE_WIDGET_WIDTH_PCT 30

#define WIFI_CONNE_WIDGET_ALIGN_TOP 5
#define WIFI_CONNE_WIDGET_ALIGN_TOP0 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP1 0
#define WIFI_CONNE_WIDGET_ALIGN_TOP2 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP3 0
#define WIFI_CONNE_WIDGET_ALIGN_TOP4 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP5 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP6 1
#define WIFI_CONNE_WIDGET_ALIGN_TOP7 0

#define WIFI_CONN_WIDGET_SET_H 0
#define WIFI_MAX_PWD_LEN 64
#endif
void lv_pro_connect_wifi_init(void *obj);

#endif /* ENABLE_WIFI */

#endif /* LV_PRO_CONNECT_WIFI_ACTIVITY_H */
