/*
 * lv_pro_selectbox_wifi.h
 *
 *  Created on: 2024/10/17
 *      Author: JASON
 */

#ifndef LV_PRO_WIFI_SELECTBOX_WIFI_H
#define LV_PRO_WIFI_SELECTBOX_WIFI_H

#include "lv_pro_wifi_common.h"

#if ENABLE_WIFI

#if defined(LV_USE_RESOLUTION_1080P)
#define WIFI_MAX_PWD_LEN 64

#define WIFI_CONN_WIDGET_SET_H 1
#define WIFI_CONN_WIGGET_WIDHT_PCT 35
#define WIFI_CONN_WIGGET_HEIHTH_PCT 20
#define WIFI_CONN_WIGGET_ALIGN_TOP1 0
#define WIFI_CONN_WIGGET_ALIGN_TOP2 0
#define WIFI_CONN_WIGGET_ALIGN_TOP3 0
#define WIFI_CONN_WIGGET_ALIGN_TOP4 10
#define WIFI_CONN_KEYPAD_HEIGHT 38

#define WIFI_DISCONN_WIDGET_SET_H 1
#define WIFI_IP_MSG_PAD_HOR -1
#define WIFI_IP_MSG_SUB_LIST_PAD_VER -1
#define WIFI_DISCONN_WIGGET_WIDHT_PCT 35
#define WIFI_DISCONN_WIGGET_HEIHTH_PCT 60
#define WIFI_ADD_HIDDEN_NET_WIDTH 35
#define WIFI_ADD_HIDDEN_NET_HEIGHT 45
#define WIFI_ADD_HIDDEN_DROP_OBJ_WIDTH 40

#define WIFI_ADD_HIDDEN_DROP_OBJ_LIST_LINE_SPACE -1
#define WIFI_ADD_HIDDEN_DROP_OBJ_LIST_PAD -1

#define WIFI_NEW_PWD_WIDGET_H 28
#define WIFI_NEW_PWD_WIDGET_W 40
#else
#define WIFI_MAX_PWD_LEN 64

#define WIFI_CONN_WIDGET_SET_H 1
#define WIFI_CONN_WIGGET_WIDHT_PCT 35
#define WIFI_CONN_WIGGET_HEIHTH_PCT 20
#define WIFI_CONN_WIGGET_ALIGN_TOP1 0
#define WIFI_CONN_WIGGET_ALIGN_TOP2 0
#define WIFI_CONN_WIGGET_ALIGN_TOP3 0
#define WIFI_CONN_WIGGET_ALIGN_TOP4 10
#define WIFI_CONN_KEYPAD_HEIGHT 38

#define WIFI_DISCONN_WIDGET_SET_H 1
#define WIFI_IP_MSG_PAD_HOR -1
#define WIFI_IP_MSG_SUB_LIST_PAD_VER -1
#define WIFI_DISCONN_WIGGET_WIDHT_PCT 35
#define WIFI_DISCONN_WIGGET_HEIHTH_PCT 60
#define WIFI_ADD_HIDDEN_NET_WIDTH 35
#define WIFI_ADD_HIDDEN_NET_HEIGHT 45
#define WIFI_ADD_HIDDEN_DROP_OBJ_WIDTH 40

#define WIFI_ADD_HIDDEN_DROP_OBJ_LIST_LINE_SPACE -1
#define WIFI_ADD_HIDDEN_DROP_OBJ_LIST_PAD -1

#define WIFI_NEW_PWD_WIDGET_H 28
#define WIFI_NEW_PWD_WIDGET_W 40
#endif

void lv_pro_selectbox_wifi_init(void *obj, int state_enum);

#endif /* ENABLE_WIFI */

#endif /* LV_PRO_WIFI_SELECTBOX_WIFI_H */