/* Copyright (c) 2019-2035 Allwinner Technology Co., Ltd. ALL rights reserved.

 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.

 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.


 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef PROJECTOR_CONFIG_H
#define PROJECTOR_CONFIG_H

#define VERSION_NAME    "H135-P1-"

/*
*   wireless screen project
*/
#define ENABLE_MIRACAST     (1)
#define ENABLE_DLNA         (1)
#define ENABLE_AIRPLAY      (1)

/*
*   WIRELESS
*/
#define LV_USE_LINUX_WIFI2_MODE 1

#ifndef LV_USE_LINUX_WIFI2_MODE
#define ENABLE_WIFI (1)
#else
#define ENABLE_WIFI (1)
#endif
#ifndef LV_USE_LINUX_BT4_MODE
#define ENABLE_BT (0)
#else
#define ENABLE_BT (1)
#endif

/*
*   HDMI
*/
#define HDMI_MAX_PORT_NUM   (2)
#define ENABLE_CEC          (1)
#define ENABLE_ARC          (1)
#define ENABLE_CEC_KEY_PASS_THROUGH (1)

/*
 * SYSTEM
 */
#define ENABLE_AUTO_BURN_KEY    (0)
#define ENABLE_TEST_HDMI        (0)
#define ENABLE_FASTBOOT         (0)

/*
 *  AWActivate
 */
#define ENABLE_AW_ACTIVATE  (1)

/*
 *  Motor
 */
#define ENABLE_MOTOR        (1)

/*
 *  Key stone
 */
#define ENABLE_KSC          (1)
#define ENABLE_KEY_STONE    (1)


/*
 *  APP Setting
 */
#define ENABLE_DISK_MANAGER (1)
#define ENABLE_PQ           (1)

#endif
